name: "Homebrew Setup"
description: "Performs initial homebrew setup for use in other pipelines on MacOS"

runs:
  using: composite

  steps:
    - name: Set up Homebrew
      id: set-up-homebrew
      uses: Homebrew/actions/setup-homebrew@main
    - name: Install Git LFS
      shell: bash
      run: brew install git-lfs && git lfs install
    - name: Install DotNet
      shell: bash
      run: brew install dotnet
