name: Build CollabXR
run-name: Build CollabXR for all platforms

# Only trigger when validation succeeds
on: [push, workflow_dispatch]

# Cancel old workflows if multiple commits are pushed to the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  # Do not cancel release tags
  cancel-in-progress: ${{ !contains(github.ref, 'v1.')}}

jobs:
  build-collabxr:
    defaults:
      run:
        shell: bash

    strategy:
      fail-fast: false
      matrix:
        include:
          #   - name: "windows" # For developer testing
          #     platform: [self-hosted, Windows, X64]
          #     unity-hub-path: "C:/Program\\ Files/Unity\\ Hub/Unity\\ Hub.exe"
          #     unity-build-profile: "Assets/Settings/Build Profiles/WindowsDesktop.asset"
          #     output-binary: Collab.exe
          - name: "windows"
            platform: [self-hosted, macOS, ARM64]
            unity-hub-path: "/Applications/Unity\\ Hub.app/Contents/MacOS/Unity\\ Hub"
            unity-build-profile: "Assets/Settings/BuildProfiles/WindowsDesktop.asset"
            output-binary: CollabXR.exe
            upload-name: CollabXR-Windows.zip
          - name: "quest3"
            platform: [self-hosted, macOS, ARM64]
            unity-hub-path: "/Applications/Unity\\ Hub.app/Contents/MacOS/Unity\\ Hub"
            unity-build-profile: "Assets/Settings/BuildProfiles/QuestRelease.asset"
            output-binary: CollabXR.apk
            upload-name: CollabXR-Quest.apk
          # - name: "macos"
          #   platform: [self-hosted, macOS, ARM64]
          #   unity-hub-path: "/Applications/Unity\\ Hub.app/Contents/MacOS/Unity\\ Hub"
          #   unity-build-profile: "Assets/Settings/BuildProfiles/MacOSDesktop.asset"
          #   output-binary: CollabXR.App

    runs-on: ${{ matrix.platform }}
    environment: ${{ github.event.inputs.environment }}

    steps:
      - name: Authenticate Envision Actions
        uses: actions/create-github-app-token@v3
        id: app-token
        with:
          client-id: ${{ vars.APP_CLIENT_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@main
      - name: Install Git LFS
        shell: bash
        run: brew install git-lfs && git lfs install
      - name: Checkout CollabXR Repository
        uses: actions/checkout@v7
        with:
          lfs: true
          submodules: true
          # token: ${{ steps.app-token.outputs.token }}
          token: ${{ secrets.ACCESS_TOKEN }}
          ref: ${{ github.head_ref }}
          # Make sure the value of GITHUB_TOKEN will not be persisted in repo's config
          persist-credentials: false
          set-safe-directory: false

      # - name: Pull Git LFS
      #   shell: bash
      #   run: git lfs pull

      # - name: Setup CollabXR
      #   id: setup
      #   uses: ./.github/composite/setup
      #   with:
      #     unity-hub: "/Applications/Unity\\ Hub.app/Contents/MacOS/Unity\\ Hub"
      #     unity-version: ${{ vars.UNITY_VERSION }}
      #     keystore: ${{ secrets.COLLAB_KEYSTORE }}
      #     token: ${{ secrets.ACCESS_TOKEN }}
      #     photon-install-path: $GITHUB_WORKSPACE/Assets

      # - name: Build CollabXR
      #   id: build
      #   uses: ./.github/composite/build
      #   with:
      #     unity: ${{ steps.setup.outputs.unity }}
      #     build-profile: ${{ matrix.unity-build-profile }}
      #     keystore-password: ${{ secrets.COLLAB_KEYSTORE_PASSWORD }}
      #     output-name: ${{ matrix.output-binary }}

      # # Configure AWS
      # - name: Upload Artifact
      #   id: upload
      #   uses: ./.github/composite/upload
      #   with:
      #     access-key: ${{ vars.AWS_ACCESS_KEY }}
      #     secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     region: ${{ secrets.S3_REGION }}
      #     bucket: ${{ secrets.S3_BUCKET }}
      #     filepath: ${{ steps.build.outputs.filepath }}
      #     filename: ${{ matrix.upload-name }}

      - name: Notify
        id: notify
        # if: ${{ secrets.EC_WEBHOOK != null }}
        shell: bash
        env: # Find a commit message or something to provide extra details
          MESSAGE: ${{ github.event.head_commit.message || github.event.workflow_run.head_commit.message || github.event.pull_request.title || github.sha }}
        # Notify developers that build finished
        run: |
          echo ${MESSAGE:q}
          curl -i -H "Accept: application/json" -H "Content-Type:application/json" -X POST --data "{\"content\": \"**${GITHUB_REF_NAME}** ${{ matrix.name }} (${{ steps.upload.outputs.file-size || '(no file)' }} KB): ${{ steps.upload.outputs.artifact-url || '(no url provided)' }}\n> ${MESSAGE:q}\"}" ${{ secrets.EC_WEBHOOK }}
