name: Build CollabXR
run-name: Build CollabXR for all platforms

# Only trigger when validation succeeds
on:
  workflow_run:
    workflows: ["Validate Code"]
    types:
      - completed
  workflow_dispatch:

jobs:
  build-collabxr:
    defaults:
      run:
        shell: bash

    strategy:
      fail-fast: false
      matrix:
        include:
          #   - name: "windows"
          #     platform: [self-hosted, Windows, X64]
          #     unity-hub-path: "C:/Program\\ Files/Unity\\ Hub/Unity\\ Hub.exe"
          #     unity-build-profile: "Assets/Settings/Build Profiles/WindowsDesktop.asset"
          #     output-binary: Collab.exe
          #     upload-path:
          - name: "windows"
            platform: [self-hosted, macOS, ARM64]
            unity-hub-path: "/Applications/Unity\\ Hub.app/Contents/MacOS/Unity\\ Hub"
            unity-build-profile: "Assets/Settings/BuildProfiles/WindowsDesktop.asset"
            output-binary: CollabXR.exe
            upload-path: CollabXR.exe
          - name: "quest3"
            platform: [self-hosted, macOS, ARM64]
            unity-hub-path: "/Applications/Unity\\ Hub.app/Contents/MacOS/Unity\\ Hub"
            unity-build-profile: "Assets/Settings/BuildProfiles/QuestRelease.asset"
            output-binary: CollabXR.apk
            upload-path: CollabXR.apk
          - name: "macos"
            platform: [self-hosted, macOS, ARM64]
            unity-hub-path: "/Applications/Unity\\ Hub.app/Contents/MacOS/Unity\\ Hub"
            unity-build-profile: "Assets/Settings/BuildProfiles/MacOSDesktop.asset"
            output-binary: CollabXR.App
            upload-path: CollabXR.App

    runs-on: ${{ matrix.platform }}
    environment: ${{ github.event.inputs.environment }}

    steps:
      - name: Authenticate Envision Actions
        uses: actions/create-github-app-token@v3
        id: app-token
        with:
          client-id: ${{ vars.APP_CLIENT_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@main
      - name: Install Git LFS
        run: brew install git-lfs && git lfs install
      - name: Checkout CollabXR Repository
        uses: actions/checkout@v7
        with:
          lfs: "true"
          submodules: "true"
          # token: ${{ steps.app-token.outputs.token }}
          token: ${{ secrets.ACCESS_TOKEN }}
          ref: ${{ github.head_ref }}
          # Make sure the value of GITHUB_TOKEN will not be persisted in repo's config
          persist-credentials: false
          set-safe-directory: false

      - name: Get Collab Keystore
        run: echo "${{ secrets.COLLAB_KEYSTORE }}" | base64 -d -o collab.keystore

      - name: Copy Photon SDK
        run: cp -r ~/Photon $GITHUB_WORKSPACE/Assets

      - name: Install Unity Editor
        continue-on-error: true
        run: ${{ matrix.unity-hub-path }} -- --headless install --version ${{ vars.UNITY_VERSION }}

      - name: Install Unity Editor Modules
        continue-on-error: true
        run: ${{ matrix.unity-hub-path }} -- --headless install-modules --version ${{ vars.UNITY_VERSION }} --module windows-mono mac-mono android --childModules

      - name: Get Unity Editor Executable Paths for Windows
        if: matrix.platform[1] == 'Windows'
        shell: pwsh
        run: |
          echo "UNITY_PATH=\"C:/Program Files/Unity/Hub/Editor/${{ vars.UNITY_VERSION }}/Editor/Unity.exe\"" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          echo "ANDROID_SDKMANAGER_PATH=\"C:/Program Files/Unity/Hub/Editor/${{ vars.UNITY_VERSION }}/Editor/Data/PlaybackEngines/AndroidPlayer/SDK/cmdline-tools/16.0/bin/sdkmanager.bat\"" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Get Unity Editor Executable Paths for MacOS
        if: matrix.platform[1] == 'macOS'
        run: |
          export UNITY_PATH="$(${{ matrix.unity-hub-path }} -- --headless install-path)/${{ vars.UNITY_VERSION }}/Unity.app/Contents/MacOS/Unity"
          echo "UNITY_PATH=${UNITY_PATH}" >> "$GITHUB_ENV"
          export ANDROID_SDKMANAGER_PATH="$(${{ matrix.unity-hub-path }} -- --headless install-path)/${{ vars.UNITY_VERSION }}/PlaybackEngines/AndroidPlayer/SDK/cmdline-tools/16.0/bin/sdkmanager"
          echo "ANDROID_SDKMANAGER_PATH=${ANDROID_SDKMANAGER_PATH}" >> "$GITHUB_ENV"

      - name: Accept Android SDK Licenses
        continue-on-error: true
        run: |
          yes | "${{ env.ANDROID_SDKMANAGER_PATH }}" --licenses

      - name: Build CollabXR Executable
        run: |
          COLLAB_KEYSTORE_PASSWORD=${{ secrets.COLLAB_KEYSTORE_PASSWORD }} "${{ env.UNITY_PATH }}" -quit -batchmode -nographic -silent-crashes -logFile - -projectPath ${{ github.workspace }} -activeBuildProfile "${{ matrix.unity-build-profile }}" -build "${{ github.workspace }}/Build/${{ matrix.output-binary }}"

      - name: List Build Outputs
        run: |
          ls ${{ github.workspace }}/Build/

      - name: Strip Debug Info
        continue-on-error: true
        run: |
          rm -rf ${{ github.workspace }}/Build/CollabXR_BurstDebugInformation_DoNotShip

      # Configure AWS
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ vars.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.S3_REGION }}
      - name: Configure AWS CLI
        run: brew install awscli
      - name: Get Build Version
        run: |
          brew install yq
          echo "BUNDLE_VERSION=$(yq '.PlayerSettings.bundleVersion' ${{ github.workspace }}/ProjectSettings/ProjectSettings.asset)" >> $GITHUB_ENV
      - name: Construct Upload Path
        run: |
          echo "FOLDER_NAME=${GITHUB_REF_NAME}-v${BUNDLE_VERSION//\"/}-run-${{github.run_id}}-${GITHUB_RUN_ATTEMPT}" >> $GITHUB_ENV
          echo "S3_PATH=s3://${{ vars.S3_BUCKET }}" >> $GITHUB_ENV

      # Tag actions with artifact uploads
      - name: Compress and Upload Desktop Artifact
        if: matrix.name != 'quest3'
        run: |
          zip -r ${{matrix.name}}.zip ${{ github.workspace }}/Build/${{ matrix.upload-path }}
          aws s3 cp ${{matrix.name}}.zip $S3_PATH/$FOLDER_NAME/
      - name: Upload Quest Artifact to S3
        if: matrix.name == 'quest3'
        run: |
          aws s3 cp ${{ github.workspace }}/Build/${{ matrix.output-binary }} $S3_PATH/$FOLDER_NAME/
      - name: Output Desktop Build
        if: matrix.name != 'quest3'
        run: |
          echo "${{matrix.name}} build: https://${{ vars.S3_BUCKET }}.s3.${{ vars.S3_REGION }}.amazonaws.com/$FOLDER_NAME/${{matrix.name}}.zip" > $GITHUB_STEP_SUMMARY
      - name: Output Quest Build
        if: matrix.name == 'quest3'
        run: |
          echo "${{matrix.name}} build: https://${{ vars.S3_BUCKET }}.s3.${{ vars.S3_REGION }}.amazonaws.com/$FOLDER_NAME/${{ matrix.output-binary }}" > $GITHUB_STEP_SUMMARY

      # - name: Upload CollabXR Executable
      #   uses: actions/upload-artifact@v7
      #   with:
      #     name: ${{ matrix.name }}-build
      #     path: ${{ github.workspace }}/Build/${{ matrix.upload-path }}
