name: Validate Code
run-name: Performs simple code analysis for CollabXR
on: [push, workflow_dispatch]

jobs:
  validate-code:
    defaults:
      run:
        shell: bash
    runs-on: [self-hosted, macOS, ARM64]
    environment: ${{ github.event.inputs.environment }}

    permissions:
      id-token: write
      contents: read
      actions: write
      statuses: write

    env:
      unity-hub: "/Applications/Unity\\ Hub.app/Contents/MacOS/Unity\\ Hub"

    steps:
      - name: Authenticate Envision Actions
        uses: actions/create-github-app-token@v3
        id: app-token
        with:
          client-id: ${{ vars.APP_CLIENT_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@main
      - name: Install Packages
        shell: bash
        run: brew install git-lfs dotnet && git lfs install

      - name: Checkout CollabXR Repository
        uses: actions/checkout@v7
        with:
          lfs: "true"
          submodules: "true"
          # token: ${{ steps.app-token.outputs.token }}
          token: ${{ secrets.ACCESS_TOKEN }}
          ref: ${{ github.head_ref }}
          # Make sure the value of GITHUB_TOKEN will not be persisted in repo's config
          persist-credentials: false
          set-safe-directory: false

      - name: Setup CollabXR
        id: setup
        uses: ./.github/composite/collabxr
        with:
          unity-hub: "/Applications/Unity\\ Hub.app/Contents/MacOS/Unity\\ Hub"
          unity-version: ${{ vars.UNITY_VERSION }}
          keystore: ${{ secrets.COLLAB_KEYSTORE }}
          token: ${{ secrets.ACCESS_TOKEN }}
          photon-install-path: $GITHUB_WORKSPACE/Assets

      - name: Run Unity Tests
        shell: bash
        run: ${{ steps.setup.outputs.unity }} -runTests -batchmode -projectPath . -testResults results.xml -testPlatform PS4

      - name: Dotnet Build
        shell: bash
        run: dotnet build CollabXR.sln

      # TODO: upload test artifact if we even want it, or report test results somehow
