name: Validate Code
run-name: Performs simple code analysis for CollabXR
# on: [push, workflow_dispatch]
on: [push] # Disabled for now until we actually have unit tests

jobs:
  validate-code:
    defaults:
      run:
        shell: bash
    runs-on: [self-hosted, macOS, ARM64]
    environment: ${{ github.event.inputs.environment }}

    permissions:
      id-token: write
      contents: read
      actions: write
      statuses: write

    env:
      unity-hub: "/Applications/Unity\\ Hub.app/Contents/MacOS/Unity\\ Hub"

    steps:
      - name: Authenticate Envision Actions
        uses: actions/create-github-app-token@v3
        id: app-token
        with:
          client-id: ${{ vars.APP_CLIENT_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@main
      - name: Install Packages
        shell: bash
        run: brew install git-lfs dotnet && git lfs install

      - name: Checkout CollabXR Repository
        uses: actions/checkout@v7
        with:
          lfs: "true"
          submodules: "true"
          # token: ${{ steps.app-token.outputs.token }}
          token: ${{ secrets.ACCESS_TOKEN }}
          ref: ${{ github.head_ref }}
          # Make sure the value of GITHUB_TOKEN will not be persisted in repo's config
          persist-credentials: false
          set-safe-directory: false

      - name: Setup CollabXR
        id: setup
        uses: ./.github/composite/collabxr
        with:
          unity-hub: "/Applications/Unity\\ Hub.app/Contents/MacOS/Unity\\ Hub"
          unity-version: ${{ vars.UNITY_VERSION }}
          keystore: ${{ secrets.COLLAB_KEYSTORE }}
          token: ${{ secrets.ACCESS_TOKEN }}
          photon-install-path: $GITHUB_WORKSPACE/Assets

      # - uses: game-ci/unity-test-runner@main
      #   # env:
      #     # UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      #     # UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      #     # UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
      #   with:
      #     projectPath: $GITHUB_WORKSPACE
      #     githubToken: ${{ secrets.GITHUB_TOKEN }}

      # https://github.com/needle-mirror/com.unity.test-framework/blob/master/Documentation~/reference-command-line.md
      # Note this command may take a while to run during initial compile
      - name: Run Unity Tests
        shell: bash
        run: ( ${{ steps.setup.outputs.unity }} -runTests -batchmode -nographic -projectPath . -testResults results.xml -quitTimeout 60 -playerHeartbeatTimeout 30 && cat results.xml ) || echo "Tests failed to run"

      # Project files aren't generated in same directory on mac for some reason
      # - name: Dotnet Build
      #   shell: bash
      #   # NOTE: .slnx is project file for macOS, .sln is project file for Windows
      #   run: ls && dotnet build CollabXR.slnx

      # TODO: upload test artifact if we even want it, or report test results somehow
